RUN_DIR: null
RESTART: ???  # SHOULD BE NULL
MODEL: null
PRETRAINED_GENERATOR: null
PRETRAINED_DISCRIMINATOR: null
AMP_ENABLE: false
SEED: 0

MAX_STEP: 200000
VAL_INTERVAL: 200
PRINT_INTERVAL: 50
TENSORBOARD_INTERVAL: 25
IMAGE_INTERVAL: 500
SAVE_INTERVAL: 1000

DATA: 
  TRAIN_DATA_DIR: ./data/DIV2K_TRAIN_HR/
  VAL_DATA_DIR: ./data/DIV2K_VALID_HR/
  TRAIN_BATCH_SIZE: 16
  VAL_BATCH_SIZE: 1
  NUM_WORKERS: 4

TRAIN: 
  LR: 1e-4
  STEP_SIZE: 100000
  GAMMA: 0.1

  CLIP_GRAD: 1.0
  MONITOR: 'lpips'
  MODE: 'min'
